spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: user-module
              uri: lb://USER-MODULE
              predicates:
                - Path=/api/v1/users/**
server:
  port: 8222