spring:
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  r2dbc:
    username: "postgres"
    password: "1115"
    url: "r2dbc:postgresql://localhost:5432/webflux_auth"
  webflux:
    base-path: /api/v1
logging:
  level:
    org.springframework.r2dbc: "DEBUG"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

server:
  port: 8810